import productImg from "../../assets/productImg.svg";

export const productItem = [
  {
    id: 0,
    img: productImg,
    newPrice: "13.999AMD",
    oldPrice: "14.000AMD",
    information: "ANMEX 6x6 Rain Shower Head with 15inch Arm",
  },
  {
    id: 1,
    img: productImg,
    newPrice: "13.999AMD",
    oldPrice: "14.000AMD",
    information: "ANMEX 6x6 Rain Shower Head with 15inch Arm",
  },
  {
    id: 2,
    img: productImg,
    newPrice: "13.999AMD",
    oldPrice: "14.000AMD",
    information: "ANMEX 6x6 Rain Shower Head with 15inch Arm",
  },
  {
    id: 3,
    img: productImg,
    newPrice: "13.999AMD",
    oldPrice: "14.000AMD",
    information: "ANMEX 6x6 Rain Shower Head with 15inch Arm",
  },
  {
    id: 4,
    img: productImg,
    newPrice: "13.999AMD",
    oldPrice: "14.000AMD",
    information: "ANMEX 6x6 Rain Shower Head with 15inch Arm",
  },
  {
    id: 5,
    img: productImg,
    newPrice: "13.999AMD",
    oldPrice: "14.000AMD",
    information: "ANMEX 6x6 Rain Shower Head with 15inch Arm",
  },
  {
    id: 6,
    img: productImg,
    newPrice: "13.999AMD",
    oldPrice: "14.000AMD",
    information: "ANMEX 6x6 Rain Shower Head with 15inch Arm",
  },
  {
    id: 7,
    img: productImg,
    newPrice: "13.999AMD",
    oldPrice: "14.000AMD",
    information: "ANMEX 6x6 Rain Shower Head with 15inch Arm",
  },
  {
    id: 8,
    img: productImg,
    newPrice: "13.999AMD",
    oldPrice: "14.000AMD",
    information: "ANMEX 6x6 Rain Shower Head with 15inch Arm",
  },
  {
    id: 9,
    img: productImg,
    newPrice: "13.999AMD",
    oldPrice: "14.000AMD",
    information: "ANMEX 6x6 Rain Shower Head with 15inch Arm",
  },
  {
    id: 10,
    img: productImg,
    newPrice: "13.999AMD",
    oldPrice: "14.000AMD",
    information: "ANMEX 6x6 Rain Shower Head with 15inch Arm",
  },
  {
    id: 11,
    img: productImg,
    newPrice: "13.999AMD",
    oldPrice: "14.000AMD",
    information: "ANMEX 6x6 Rain Shower Head with 15inch Arm",
  },
  {
    id: 12,
    img: productImg,
    newPrice: "13.999AMD",
    oldPrice: "14.000AMD",
    information: "ANMEX 6x6 Rain Shower Head with 15inch Arm",
  },
  {
    id: 13,
    img: productImg,
    newPrice: "13.999AMD",
    oldPrice: "14.000AMD",
    information: "ANMEX 6x6 Rain Shower Head with 15inch Arm",
  },
  {
    id: 14,
    img: productImg,
    newPrice: "13.999AMD",
    oldPrice: "14.000AMD",
    information: "ANMEX 6x6 Rain Shower Head with 15inch Arm",
  },
];
